# Generated by Django 3.2.3 on 2023-08-24 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_availability_app', '0003_alter_datapoint_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 24, 15, 46, 49, 613224), null=True),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
